# Generated by Django 5.0.7 on 2024-07-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_activ_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Ключ'),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ID оплаты'),
        ),
    ]
